### PR TITLE
update to 3.0.6

### PR DESCRIPTION
**Pull request by Maarten-vd-Sande**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Maarten-vd-Sande** [comment]
@conda-forge-admin, please rerender

**Comment by dpryan79** [comment]
@Maarten-vd-Sande This looks good and would fix something that I literally just ran into :) Is there anything else you think it needs before we ping @gioelelm

**Comment by Maarten-vd-Sande** [comment]
Nope, this should work, I just got distracted by something else... I am not sure why it won't rerender (also not sure what that does).

**Comment by dpryan79** [comment]
@conda-forge-admin please rerender

**Comment by dpryan79** [comment]
If the bot doesn't rerender in a bit I'll do it locally.

**Comment by dpryan79** [comment]
@Maarten-vd-Sande Can you make sure you have the "Allow edis from maintainers" box checked?

**Comment by Maarten-vd-Sande** [comment]
It's turned on (from the beginning).

image

I just turned it off and on again, maybe that does something?

**Comment by Maarten-vd-Sande** [comment]
@conda-forge-admin please rerender

**Comment by Maarten-vd-Sande** [comment]
@dpryan79 if it's still causing problems feel free to start a new PR, might be easier

**Comment by dpryan79** [comment]
Sounds like a plan, I'll make a new PR based on yours

**Pull request closed without merging**
